# Generated by Django 3.1.12 on 2025-11-11 18:55

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0003_auto_20251112_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='resume',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='self_introduction',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='uploads/'),
        ),
    ]
